### ISSUE TITLE
Example of image hosting?

### ISSUE THREAD

**Issue by ricopicone** [manuvazquez/py2gift#1]
Great project! Do you have a recommendation for or example of image hosting? I was thinking I'd probably use github because it looks like `py2gift` uses ssh. Does that make sense?

**Comment by manuvazquez** [comment]
Thanks for the kind words!! To be honest you got me on this one :) Can you ssh into github? I don't know, but it'd be very cool. I've been using a server provided by my organization. As you mention, py2gift (relying on gift-wrapper underneath) just uses ssh, so any machine to which you can ssh (either via public-key infrastructure or login/password) should be fine. You can also skip this completely and embed the images (I did that for my last quiz and it was fine).

**Comment by ricopicone** [comment]
Interesting ... the "embed" option is attractive; does it require my (institution's) Moodle be configured with the plugin "GIFT with medias format" that accepts zipped questions, bundled with the images? 

Github does allow ssh authentication for connections, so there might be a way to have a public repo expose images ... if I go this route I'll report back. Thanks, again!

**Comment by manuvazquez** [comment]
No, the "embed" option doesn't require any Moodle plugin. What it does is to actually embed the svg file into plain html code. The (sort of) drawback is that nor the generated GIF file nor the corresponding questions (once the former is imported in Moodle) are very human-readable anymore (since the image path is replaced with a bunch of SVG-related coordinates and tags). That is fine, though, if (like me) you don't intend to, afterwards, edit the questions from within Moodle.

**Comment by ricopicone** [comment]
Ah, that’s smooth! I’ll give it a try.
