### ISSUE TITLE
Example using py2gift without jupyter

### ISSUE THREAD

**Issue by rangerjo** [manuvazquez/py2gift#2]
I was very happy I found this work. The code looks well designed. However, I would like to use the module without jupyter, allowing to use a proper text editor and simultaneously rendering to a .tex-file for developement. My first attempt constructing a question with a statement and feedback and generating the gift file failed.
Would you be willing to provide a minimal example to generate a statement, feedback and question and show how to export it to a gift file? That would be great. Anyways, thanks a lot for your great work!

**Comment by manuvazquez** [comment]
I'm glad you find the software useful!! I take it you mean "rendering to a *text* file", right? It would be cool to output TeX files (I even entertained the possibility when designing the whole thing) but since, unfortunately, it's not supported by Moodle, it would be of very little use. Anyway, if you just want to use the software without jupyter, that should be fine. I added a new directory "jupyterless" inside the existing "examples" directory. There, inside sub-directory "example_1", you can find the files that are required to reproduce "example_1" without jupyter. Also, I added a [mini-HOWTO](https://github.com/manuvazquez/py2gift/blob/master/examples/jupyterless/HOWTO.md) shows exactly how to run the code. Hope, it helps.

**Comment by rangerjo** [comment]
Wow that was quick! And exactly what I was looking for. Thank you very much.
And yes, I meant rendering to a TeX file. I have a bunch of questions with tikz figures showing computer network topologies and I might want to randomize MAC/IP/Subnet aso. In addition, generating TeX files leaves the possibility to return to conventional paper tests.

For those interested, the following code also allows to generate a preview.html. Maybe this might be something you would want to add to the mini-HOWTO.

```
import importlib
import py2gift.core
import py2gift.util
import yaml
import markdown

generators = importlib.import_module('generators')

py2gift.core.build('settings.yaml', True, generators, 'parameters.yaml', no_checks=True, embed_images=True)

settings = dict()
with open('settings.yaml', 'r') as file:
    settings = yaml.load(file, Loader=yaml.SafeLoader)

with open('preview.html', 'w') as file:
    for question in settings['categories']:
        file.write(markdown.markdown('# {}'.format(question['name'])))
        out_md = py2gift.util.render_latex(py2gift.core.generator_to_markdown(settings, question['name'], getattr(generators, question['classes'][0]['name'])))
        out_html = markdown.markdown(out_md.data)
        file.write(out_html)
```

Many thanks!
